### PR TITLE
QBDI 0.7.0 Release candidate 

### PR DESCRIPTION
**Pull request by romainthomas**

### CODE REVIEW

**Comment by nezetic** [comment]
If you have changed things in Frida bindings in term of APIs support, don't forget to bump the version.
Be also careful with things like ArchLinux PKGBUILD files, as versions are still unfortunately not in sync everywhere.

**Comment by romainthomas** [comment]
We didn't touch to Frida-JS. We are working on an easiest integration using [Gum Interceptor](https://github.com/frida/frida-gum/blob/79d5f4d6bf7b31eebca6918b7d403a34d844cb66/gum/guminterceptor.h#L39-L69) 

The idea is to use Frida's low level API to hook functions and then create an instance of QBDI using the context provided by Frida: 

```cpp
GumInvocationContext* ctx = gum_interceptor_get_current_invocation();
QBDI::GPRState* state = vm.getGPRState();
state->x0  = ctx->cpu_context->x[0];
state->x1  = ctx->cpu_context->x[1];
state->x2  = ctx->cpu_context->x[2];
...
vm.setGPRState(state);
```
Regarding this injection, it will be done through Frida's [inject_library_blob](https://github.com/frida/frida-python/blob/7def1ad210cd85f2db6c62bdd470582bf237ad1a/frida/__init__.py#L69)

**Comment by nezetic** [comment]
Master doesn't compile on my mac, because _/usr/include/mach/mach_exc.defs_ does not exist.
This file is probably not created anymore when installing _Xcode_ and _Command Line Tools_.

I had to point directly to the SDK (not really a clean fix though).

```patch
diff --git a/tools/QBDIPreload/CMakeLists.txt b/tools/QBDIPreload/CMakeLists.txt
index d7d0650..fb63273 100644
--- a/tools/QBDIPreload/CMakeLists.txt
+++ b/tools/QBDIPreload/CMakeLists.txt
@@ -4,7 +4,8 @@ if((${OS} STREQUAL "linux") OR (${OS} STREQUAL "android"))
     set(SOURCES ${SOURCES} "src/linux_preload.c")
 elseif(${OS} STREQUAL "macOS")
     # Generate MIG interface at config time in the build directory
-    execute_process(WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR} COMMAND mig /usr/include/mach/mach_exc.defs)
+    set(MACHEXC_DEFS /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/mach/mach_exc.defs)
+    execute_process(WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR} COMMAND mig ${MACHEXC_DEFS})
     set(SOURCES ${SOURCES} "src/darwin_preload.c" "src/darwin_exceptd.c" "mach_excServer.c")
 endif()
 

```

**Comment by nsurbay** [comment]
> Master doesn't compile on my mac, because _/usr/include/mach/mach_exc.defs_ does not exist.
> This file is probably not created anymore when installing _Xcode_ and _Command Line Tools_ (my install is a fresh one from 4 months ago).
> 
> I had to point directly to the SDK (not really a clean fix though).
> 
> ```diff
> diff --git a/tools/QBDIPreload/CMakeLists.txt b/tools/QBDIPreload/CMakeLists.txt
> index d7d0650..fb63273 100644
> --- a/tools/QBDIPreload/CMakeLists.txt
> +++ b/tools/QBDIPreload/CMakeLists.txt
> @@ -4,7 +4,8 @@ if((${OS} STREQUAL "linux") OR (${OS} STREQUAL "android"))
>      set(SOURCES ${SOURCES} "src/linux_preload.c")
>  elseif(${OS} STREQUAL "macOS")
>      # Generate MIG interface at config time in the build directory
> -    execute_process(WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR} COMMAND mig /usr/include/mach/mach_exc.defs)
> +    set(MACHEXC_DEFS /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/mach/mach_exc.defs)
> +    execute_process(WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR} COMMAND mig ${MACHEXC_DEFS})
>      set(SOURCES ${SOURCES} "src/darwin_preload.c" "src/darwin_exceptd.c" "mach_excServer.c")
>  endif()
>  
> ```

The CI and the mac I used to build the package don't have this problem. Can you check if the commit 601f7c5afee596ba9df3ec2391efa1931afae0cf can fix the issue ?

**Comment by nezetic** [comment]
Indeed, commit 601f7c5 fixes the issue in a cleaner way.

**Pull request merged**
