### PR TITLE
Migrate to llvm 7.0.0

### PR DESCRIPTION
**Pull request by pbrunet**

### CODE REVIEW

**Comment by pbrunet** [comment]
I will not have time to finish this now. Feel free to reuse what is done here otherwise, I will continue at the begining of november.

**Comment by pbrunet** [comment]
This MR Should be OK. It perform:
* Migration to llvm 7
* Fix packaging in travis.yml to really install ccache
* Update cache information on travis to save less data and avoid caching build.sh to use our version when there is an update
* Compile only used libraries for LLVM
* Rework the build system for LLVM.

The Rework for the llvm buildsystem may be questionable and not be part of this MR. I did it because travis was not fast enought to compile llvm so I update the build.sh to perform less computation. Then I have to update every others build.sh just like I did when I update the llvm version. It show me that most of the script is a duplication so I factorize everything in build.py and finally, only cmake flags are really platform dependent.

**Comment by pbrunet** [comment]
I don't have right to rerun the appveyor CI but it validated on my appveyor account.

**Comment by romainthomas** [comment]
@pbrunet I tried to compile for Android and you should add ``LLVMARMUtils.a`` here:
https://github.com/QBDI/QBDI/blob/c498ff22eb73600232610cca376c204da10af8e1/CMakeLists.txt#L202

**Comment by pbrunet** [comment]
I signed my commits.

**Comment by romainthomas** [comment]
Merged!

**Pull request closed without merging**
